### ISSUE TITLE
Vagrant box doesn't work

### ISSUE THREAD

**Issue by countgizmo** [6D65/shovelleros#3]
After adding the box and doing `vagrant init cocosdev` I run `vagrant up` and then get this message back multiple times until it times out: _default: Warning: Authentication failure. Retrying..._

**Comment by 6D65** [comment]
That's an issue with  Vagrant. For whatever reason when creating a box based on a precise32 box, the authentication is broken. The solution would be to clone the shovellerosdev which is another box based on the cocosdev box(and has the fix for this), during its deployment it will clone the shovellers repo.

``` bash
git clone https://github.com/6D65/shovellerosdev.git
cd shovellerosdev
vagrant up
```

To start the shovelleros game, you would want to ssh into the shovellerosdev machine, and start the game server.

``` bash
vagrant ssh
cd /vargrant/shovelleros
cocos run -p web --host 0.0.0.0
```

then browse from the local machine to localhost:8080, the local repo of the shovelleros will be available from the shovellerosdev folder, an can be worked/commited from the host machine.

``` bash
- shovellerosdev
  - shovelleros // The shovelleros repo cloned by the vagrant build script
```

**It's very important to keep the cocosdev image, since the shovellerosdev is based on it.**

**Comment by 6D65** [comment]
Updated the shovellers repo with the latest bootstrap script, everything should work now.
